name: Deploy lambda
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main-destroy
jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: hashicorp/setup-terraform@v3
      - name: Destroy infrastructure
        run: |
          echo "Deploying infrastructure..."
          terraform init
          terraform destroy -auto-approve